=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/schemas/CovidTestPassStandardCredentialMinimal.json
{
  "$id": "https://w3id.org/pathogen/schemas/CovidTestPassStandardCredentialMinimal.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"StandardCovidTestPassMinimal\", \"@id\": \"https://w3id.org/pathogen#CovidTestPassStandardCredentialMinimal\"}",
  "title": "StandardCovidTestPassMinimal",
  "description": "A standard Covid19 Testpass containing minimal data",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array"
        }
      ]
    },
    "testType": {
      "$comment": "{\"term\": \"testType\", \"@id\": \"https://schema.org/name\"}",
      "title": "TestType",
      "description": "Type of Covid19 test",
      "type": "string"
    },
    "testedPerson": {
      "$comment": "{\"term\": \"testedPerson\", \"@id\": \"https://schema.org/Person\"}",
      "title": "Tested Person",
      "description": "Person receiving the test",
      "$ref": "https://w3id.org/pathogen/schemas/Person.json"
    },
    "testResult": {
      "$comment": "{\"term\": \"testResult\", \"@id\": \"https://schema.org/signDetected\"}",
      "title": "testResult",
      "description": "Result of Covid19 Test",
      "type": "string"
    }
  },
  "additionalProperties": false,
  "examples": []
}

=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/src/__fixtures__/CovidTestPassStandardCredentialMinimal/good.json
[
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "StandardCovidTestPassMinimal",
    "testType": "Antigen Test",
    "testedPerson": {
      "type": "Person",
      "idnumber": "OZXWAVZGMESR",
      "idnumberType": "National Identity Card"
    },
    "testResult": "Negative"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "StandardCovidTestPassMinimal",
    "testType": "PCR Test",
    "testedPerson": {
      "type": "Person",
      "idnumber": "YWVTZKDYTZYF",
      "idnumberType": "Passport"
    },
    "testResult": "Positive"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "StandardCovidTestPassMinimal",
    "testType": "Rapid PCR Test",
    "testedPerson": {
      "type": "Person",
      "idnumber": "WQMNTXOUZDTI",
      "idnumberType": "National Identity Card"
    },
    "testResult": "Negative"
  }
]
