=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/schemas/CovidTestPassEvidenceDocument.json
{
  "$id": "https://w3id.org/pathogen/schemas/CovidTestPassEvidenceDocument.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$comment": "{\"term\": \"CovidTestPassEvidenceDocument\", \"@id\": \"https://w3id.org/pathogen#CovidTestPassEvidenceDocument\"}",
  "title": "StandardCovidTestPassDetailed",
  "description": "A standard Covid19 Testpass containing detailed data",
  "type": "object",
  "properties": {
    "@context": {
      "type": "array"
    },
    "type": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "array"
        }
      ]
    },
    "testType": {
      "$comment": "{\"term\": \"testType\", \"@id\": \"https://schema.org/name\"}",
      "title": "TestType",
      "description": "Type of Covid19 test",
      "type": "string"
    },
    "testCenter": {
      "$comment": "{\"term\": \"testCenter\", \"@id\": \"https://schema.org/Organization\"}",
      "title": "Test Center",
      "description": "Name and location of test center",
      "$ref": "https://w3id.org/pathogen/schemas/Organization.json"
    },
    "healthProfessionalAdministered": {
      "$comment": "{\"term\": \"healthProfessionalAdministered\", \"@id\": \"https://schema.org/description\"}",
      "title": "Health Professional Administration",
      "description": "Was test administered by a certified health professional",
      "type": "string"
    },
    "testedPerson": {
      "$comment": "{\"term\": \"testedPerson\", \"@id\": \"https://schema.org/Person\"}",
      "title": "Tested Person",
      "description": "Person receiving the test",
      "$ref": "https://w3id.org/pathogen/schemas/Person.json"
    },
    "testResult": {
      "$comment": "{\"term\": \"testResult\", \"@id\": \"https://schema.org/signDetected\"}",
      "title": "testResult",
      "description": "Result of Covid19 Test",
      "type": "string"
    },
    "testDetails": {
      "$comment": "{\"term\": \"testDetails\", \"@id\": \"https://schema.org/MedicalTest\"}",
      "title": "testDetails",
      "description": "Details of the used test",
      "$ref": "https://w3id.org/pathogen/schemas/MedicalTest.json"
    }
  },
  "additionalProperties": false,
  "examples": []
}

=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/src/__fixtures__/CovidTestPassEvidenceDocument/good.json
[
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "CovidTestPassEvidenceDocument",
    "testType": "PCR Test",
    "testCenter": {
      "type": "Organization",
      "name": "Weissnat Inc",
      "description": "Persistent discrete open system",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "72405 Brown Road",
        "addressLocality": "South Bernadetteville",
        "addressRegion": "Alaska",
        "postalCode": "64355-6912",
        "addressCountry": "Mozambique"
      },
      "email": "Shania_Ward@example.org",
      "phoneNumber": "555-469-5858",
      "faxNumber": "555-779-2827"
    },
    "healthProfessionalAdministered": "No",
    "testedPerson": {
      "type": "Person",
      "firstName": "Eugene",
      "lastName": "Frami",
      "email": "Cathryn51@example.net",
      "phoneNumber": "555-207-3424",
      "worksFor": {
        "type": "Organization",
        "name": "Herman, Stoltenberg and Haag",
        "description": "Adaptive clear-thinking instruction set",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "482 Trantow Estates",
          "addressLocality": "Lindgrenborough",
          "addressRegion": "South Dakota",
          "postalCode": "83391",
          "addressCountry": "Ethiopia"
        },
        "email": "Hayley69@example.com",
        "phoneNumber": "555-305-6829",
        "faxNumber": "555-484-1004"
      },
      "jobTitle": "Customer Assurance Administrator",
      "idnumber": "JBZGZGGSMSHD",
      "idnumberType": "Passport",
      "birthDate": "1985-11-23"
    },
    "testResult": "Negative",
    "testDetails": {
      "type": "MedicalTest",
      "affectedBy": [
        "High Blood Pressure Medicines"
      ],
      "normalRange": [
        "Any Person"
      ],
      "signDetected": "Positive",
      "usedToDiagnose": "Covid19 2020 Variants",
      "usesDevice": "VDINESBWPIRF",
      "code": "ASNVFJQC",
      "legalStatus": "Approved",
      "medicineSystem": "evidence-based",
      "recognizingAuthority": {
        "type": "Organization",
        "name": "Ferry - Flatley",
        "description": "Re-contextualized scalable framework",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "540 Hegmann Burgs",
          "addressLocality": "Nicolasberg",
          "addressRegion": "Ohio",
          "postalCode": "54495",
          "addressCountry": "Dominican Republic"
        },
        "email": "Lonzo.Wyman@example.com",
        "phoneNumber": "555-633-7049",
        "faxNumber": "555-172-7854"
      },
      "relevantSpecialty": "Other"
    }
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "CovidTestPassEvidenceDocument",
    "testType": "Antigen Test",
    "testCenter": {
      "type": "Organization",
      "name": "Nitzsche, Stark and Boehm",
      "description": "Upgradable clear-thinking productivity",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "2290 Keara Vista",
        "addressLocality": "Tillmanfurt",
        "addressRegion": "Georgia",
        "postalCode": "23778",
        "addressCountry": "Tokelau"
      },
      "email": "Marcella.Moen@example.net",
      "phoneNumber": "555-870-8983",
      "faxNumber": "555-464-8018"
    },
    "healthProfessionalAdministered": "No",
    "testedPerson": {
      "type": "Person",
      "firstName": "Lamar",
      "lastName": "Wiza",
      "email": "Glen_Kuhlman63@example.net",
      "phoneNumber": "555-325-3195",
      "worksFor": {
        "type": "Organization",
        "name": "Stanton, Reichert and Okuneva",
        "description": "Front-line local intranet",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "9021 Jean Grove",
          "addressLocality": "Isaiasfurt",
          "addressRegion": "Wyoming",
          "postalCode": "17024",
          "addressCountry": "Ghana"
        },
        "email": "Johann.Hilll@example.org",
        "phoneNumber": "555-260-7718",
        "faxNumber": "555-429-6846"
      },
      "jobTitle": "District Data Director",
      "idnumber": "NQORMWFFSMHO",
      "idnumberType": "Passport",
      "birthDate": "1985-11-23"
    },
    "testResult": "Negative",
    "testDetails": {
      "type": "MedicalTest",
      "affectedBy": [
        "Antibiotics"
      ],
      "normalRange": [
        "Any Person"
      ],
      "signDetected": "Positive",
      "usedToDiagnose": "Covid19 SA Variant",
      "usesDevice": "RZJDGNHWITWS",
      "code": "DSSJOHHV",
      "legalStatus": "Revoked",
      "medicineSystem": "evidence-based",
      "recognizingAuthority": {
        "type": "Organization",
        "name": "Halvorson and Sons",
        "description": "De-engineered explicit knowledge user",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "949 Shaun Gardens",
          "addressLocality": "Lake Adrienne",
          "addressRegion": "West Virginia",
          "postalCode": "34595-9980",
          "addressCountry": "France"
        },
        "email": "Tremayne_Sporer57@example.com",
        "phoneNumber": "555-375-4465",
        "faxNumber": "555-271-8660"
      },
      "relevantSpecialty": "Communicable Disease"
    }
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "CovidTestPassEvidenceDocument",
    "testType": "PCR Test",
    "testCenter": {
      "type": "Organization",
      "name": "Senger and Sons",
      "description": "Horizontal interactive benchmark",
      "address": {
        "type": "PostalAddress",
        "streetAddress": "370 Eugenia Tunnel",
        "addressLocality": "West Kolbyton",
        "addressRegion": "Michigan",
        "postalCode": "60341-5928",
        "addressCountry": "Montenegro"
      },
      "email": "Joy.Shields21@example.org",
      "phoneNumber": "555-874-1274",
      "faxNumber": "555-325-1336"
    },
    "healthProfessionalAdministered": "Unkown",
    "testedPerson": {
      "type": "Person",
      "firstName": "Demarco",
      "lastName": "Fisher",
      "email": "Aurelia66@example.com",
      "phoneNumber": "555-240-4981",
      "worksFor": {
        "type": "Organization",
        "name": "Windler Inc",
        "description": "Streamlined global open system",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "015 Maximo Lake",
          "addressLocality": "Brittanychester",
          "addressRegion": "Connecticut",
          "postalCode": "95730-7324",
          "addressCountry": "Japan"
        },
        "email": "Hailie91@example.net",
        "phoneNumber": "555-769-1706",
        "faxNumber": "555-325-1228"
      },
      "jobTitle": "Chief Response Orchestrator",
      "idnumber": "YNTROLPSKBGO",
      "idnumberType": "Passport",
      "birthDate": "1985-11-23"
    },
    "testResult": "Negative",
    "testDetails": {
      "type": "MedicalTest",
      "affectedBy": [
        "Birthcontrol"
      ],
      "normalRange": [
        "Any Person"
      ],
      "signDetected": "Negative",
      "usedToDiagnose": "Covid19 2020 Variants",
      "usesDevice": "ORREQBYQYAWP",
      "code": "QYUORKOQ",
      "legalStatus": "Approved",
      "medicineSystem": "evidence-based",
      "recognizingAuthority": {
        "type": "Organization",
        "name": "Beahan - Morissette",
        "description": "User-centric motivating success",
        "address": {
          "type": "PostalAddress",
          "streetAddress": "31000 Steuber Camp",
          "addressLocality": "Prosaccoville",
          "addressRegion": "Mississippi",
          "postalCode": "07484",
          "addressCountry": "Guadeloupe"
        },
        "email": "Devin62@example.org",
        "phoneNumber": "555-255-5182",
        "faxNumber": "555-490-6847"
      },
      "relevantSpecialty": "Other"
    }
  }
]
