=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/schemas/DGCProofOfVaccination.json
{
    "$id": "https://w3id.org/pathogen/schemas/DGCProofOfVaccination.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"DGCProofOfVaccination\", \"@id\": \"https://w3id.org/pathogen#DGCProofOfVaccination\"}",
    "title": "Proof of Covid-19 Vaccination",
    "description": "A standard Covid19 Vaccination cert containing detailed data",
    "type": "object",
    "properties": {
      "@context": {
        "type": "array"
      },
      "type": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "array"
          }
        ]
      },
      "vaccinationInformation" : {
          "$comment": "{\"term\": \"vaccinationInformation\", \"@id\": \"https://w3id.org/pathogen#DGCVaccinationInformation\"}",
          "title": "Vaccination information",
          "description": "Vaccination (event) information",
          "$ref": "https://w3id.org/pathogen/schemas/DGCVaccinationInformation.json"
      },
      "personalInformation" : {
        "$comment": "{\"term\": \"personalInformation\", \"@id\": \"https://w3id.org/pathogen#DGCSubject\"}",
        "title": "Vaccination Recipient",
        "description": "Vaccination subject (patient) information",
        "$ref": "https://w3id.org/pathogen/schemas/DGCSubject.json"
      }
    },
    "additionalProperties": false,
    "examples": []
}

=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/src/__fixtures__/DGCProofOfVaccination/good.json
[
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCProofOfVaccination",
    "vaccinationInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCVaccinationInformation",
      "administeringCentre": "Hospital Universario La Paz",
      "batchNumber": "C1235742",
      "countryOfVaccination": "de",
      "dateOfVaccination": "2021-02-22T13:19:56.397Z",
      "healthProfessional": "MSSCZN70H08H704F",
      "nextVaccinationDate": "2021-05-20T21:09:06.704Z",
      "order": "1 of 1",
      "vaccine": {
        "@context": [
          "https://w3id.org/pathogen/v1"
        ],
        "type": "DGCVaccine",
        "code": "SCT#1119349007",
        "targetDisease": "ICD-10#J12.82",
        "marketingAuthHolder": "Moderna Biotech Spain S.L.",
        "medicinalProductName": "COVID-19 Vaccine"
      }
    },
    "personalInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCSubject",
      "familyName": "Lebsack",
      "givenName": "Sheldon",
      "birthDate": "1973-01-18T02:42:23.588Z",
      "gender": "female"
    }
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCProofOfVaccination",
    "vaccinationInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCVaccinationInformation",
      "administeringCentre": "Hospital Universario La Paz",
      "batchNumber": "A1235742",
      "countryOfVaccination": "it",
      "dateOfVaccination": "2021-02-13T21:44:14.841Z",
      "healthProfessional": "VRDRCR70H08H703B",
      "nextVaccinationDate": "2021-05-27T09:31:45.220Z",
      "order": "2 of 2",
      "vaccine": {
        "@context": [
          "https://w3id.org/pathogen/v1"
        ],
        "type": "DGCVaccine",
        "code": "SCT#1119349007",
        "targetDisease": "ICD-10#J12.82",
        "marketingAuthHolder": "Novavax CZ AS",
        "medicinalProductName": "COVID-19 Vaccine"
      }
    },
    "personalInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCSubject",
      "familyName": "Watsica",
      "givenName": "Pietro",
      "birthDate": "1953-10-13T04:42:02.235Z",
      "gender": "female"
    }
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCProofOfVaccination",
    "vaccinationInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCVaccinationInformation",
      "administeringCentre": "MÃ¼nchen Klinik Bogenhausen",
      "batchNumber": "B1235742",
      "countryOfVaccination": "de",
      "dateOfVaccination": "2021-03-16T04:22:05.488Z",
      "healthProfessional": "RCSTGI90B1823661",
      "nextVaccinationDate": "2021-05-19T10:08:06.370Z",
      "order": "1 of 1",
      "vaccine": {
        "@context": [
          "https://w3id.org/pathogen/v1"
        ],
        "type": "DGCVaccine",
        "code": "SCT#1119349007",
        "targetDisease": "ICD-10#J12.82",
        "marketingAuthHolder": "Biontech Manufacturing GmbH",
        "medicinalProductName": "COVID-19 Vaccine"
      }
    },
    "personalInformation": {
      "@context": [
        "https://w3id.org/pathogen/v1"
      ],
      "type": "DGCSubject",
      "familyName": "Runte",
      "givenName": "Audra",
      "birthDate": "1972-07-23T14:44:35.992Z",
      "gender": "female"
    }
  }
]
