=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/schemas/DGCSubject.json
{
    "$id": "https://w3id.org/pathogen/schemas/DGCSubject.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"DGCSubject\", \"@id\": \"https://w3id.org/pathogen#DGCSubject\"}",
    "title": "DGCSubject",
    "description": "Lab test information for vax.",
    "type": "object",
    "properties": {
        "@context": {
            "type": "array"
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "familyName": {
          "$comment": "{\"term\": \"familyName\", \"@id\": \"http://hl7.eu/fhir/ig/dgc/Patient.name.familyName\"}",
          "title": "Family Name",
          "description": "Family name of the subject",
          "type": "string"
        },
        "givenName" : {
          "$comment": "{\"term\": \"givenName\", \"@id\": \"http://hl7.eu/fhir/ig/dgc/Patient.name.givenName\"}",
          "title": "Given Name",
          "description": "Given name of the subject",
          "type": "string"
        },
        "birthDate" : {
          "$comment": "{\"term\": \"birthDate\", \"@id\": \"http://hl7.eu/fhir/ig/dgc/Patient.birthDate\"}",
          "title": "Date of Birth",
          "description": "Subjects date of birth",
          "type": "string"
        },
        "gender" : {
          "$comment": "{\"term\": \"gender\", \"@id\": \"http://hl7.org/fhir/gender-identity\"}",
          "title": "Gender",
          "description" : "Gender of the subject",
          "type": "string"
        }

    },
    "additionalProperties": false,
    "examples": []
}

=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/src/__fixtures__/DGCSubject/good.json
[
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCSubject",
    "familyName": "Schneider",
    "givenName": "Kameron",
    "birthDate": "1979-01-27T21:25:11.340Z",
    "gender": "female"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCSubject",
    "familyName": "Zboncak",
    "givenName": "Alaina",
    "birthDate": "1950-01-05T16:25:55.345Z",
    "gender": "female"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCSubject",
    "familyName": "Heller",
    "givenName": "Amie",
    "birthDate": "1991-06-06T06:06:49.774Z",
    "gender": "female"
  }
]
