=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/schemas/DGCVaccine.json
{
    "$id": "https://w3id.org/pathogen/schemas/DGCVaccine.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$comment": "{\"term\": \"DGCVaccine\", \"@id\": \"https://w3id.org/pathogen#DGCVaccine\"}",
    "title": "DGCVaccine",
    "description": "Vaccine information",
    "type": "object",
    "properties": {
        "@context": {
            "type": "array"
        },
        "type": {
            "oneOf": [
                {
                    "type": "string"
                },
                {
                    "type": "array"
                }
            ]
        },
        "code" : {
            "$comment": "{\"term\": \"code\", \"@id\": \"http://id.who.int/icd/entity/164949870\"}",
            "title": "Vaccine code",
            "description": "Vaccine code",
            "type": "string"
        },
        "targetDisease" : {
            "$comment": "{\"term\": \"targetDisease\", \"@id\": \"http://hl7.org/fhir/Immunization.protocolApplied.targetedDisease\"}",
            "title": "Targeted Disease",
            "description": "Disease targeted by this vaccine",
            "type": "string"
        },
        "marketingAuthHolder" : {
            "$comment": "{\"term\": \"marketingAuthHolder\", \"@id\": \"http://hl7.eu/fhir/ig/dgc/ValueSet/vaccines-covid-19-auth-holders\"}",
            "title": "Marketing Auth holder",
            "description": "Marketing Auth holder",
            "type": "string"
        },
        "medicinalProductName" : {
            "$comment": "{\"term\": \"medicinalProductName\", \"@id\": \"http://hl7.eu/fhir/ig/dgc/ValueSet/vaccines-covid-19-names\"}",
            "title": "Product name",
            "description": "Product or Trade name used for the vaccine",
            "type": "string"
        }
    },
    "additionalProperties": false,
    "examples": []
}

=== SemanticClarity/Pathogen-Vocab/packages/pathogen-schemas/src/__fixtures__/DGCVaccine/good.json
[
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCVaccine",
    "code": "SCT#1119349007",
    "targetDisease": "ICD-10#J12.82",
    "marketingAuthHolder": "Novavax CZ AS",
    "medicinalProductName": "COVID-19 Vaccine"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCVaccine",
    "code": "SCT#1119349007",
    "targetDisease": "ICD-10#J12.82",
    "marketingAuthHolder": "Biontech Manufacturing GmbH",
    "medicinalProductName": "COVID-19 Vaccine"
  },
  {
    "@context": [
      "https://w3id.org/pathogen/v1"
    ],
    "type": "DGCVaccine",
    "code": "SCT#1119349007",
    "targetDisease": "ICD-10#J12.82",
    "marketingAuthHolder": "Moderna Biotech Spain S.L.",
    "medicinalProductName": "COVID-19 Vaccine"
  }
]
